/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 07 02:04:03 GMT 2018
 */

package com.wakaleo.gameoflife.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.wakaleo.gameoflife.domain.Cell;
import com.wakaleo.gameoflife.domain.GridReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GridReader_ESTest extends GridReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GridReader gridReader0 = new GridReader();
      // Undeclared exception!
      try { 
        gridReader0.loadFrom((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.wakaleo.gameoflife.domain.GridReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GridReader gridReader0 = new GridReader();
      // Undeclared exception!
      try { 
        gridReader0.loadFrom(";C9.5txQKl");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.wakaleo.gameoflife.domain.GridReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GridReader gridReader0 = new GridReader();
      Cell[][] cellArray0 = gridReader0.loadFrom("*");
      assertEquals(1, cellArray0.length);
  }
}
